version: '3.4'

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:5.7.22
    restart: "always"
    ports:
      - "23306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - './mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro'
    environment:
      MYSQL_ROOT_PASSWORD: redes2
      MYSQL_DATABASE: redes2
  
  frontend:
    build: ./frontend
    restart: "always"
    ports:
      - '10000:80'
    environment:
      REACT_APP_API_URL: http://backend:8080
      
  backend:
    build: ./backend
    restart: "always"
    depends_on:
      - mysql
    ports:
      - '10001:8080'
    environment:
      SERVER_PORT: 8080
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: redes2
      DB_NAME: redes2
